#!/bin/bash
# Wizard step 8: bring up the docker stack.

step_heading 8 9 "Bring up the stack"

if [[ "$NODEAVA_PLATFORM" = "mac" ]]; then
  say "  Starting three Docker services (Mac native path):"
  say "    • frontend      — Vite-built dashboard served by nginx (port 3000)"
  say "    • orchestrator  — the agentic-loop brain (port 8082)"
  say "    • searxng       — bundled meta-search for the browser tool"
  say ""
  say "  tts (Kokoro) and stt (Whisper) run natively on this host for Metal"
  say "  GPU acceleration. Bring those up separately:"
  say "    bash scripts/start-mac.sh"
  say ""
  say "  Ollama is also on the host (not in Docker) — :11434."
else
  say "  Starting five services:"
  say "    • frontend      — Vite-built dashboard served by nginx (port 3000)"
  say "    • orchestrator  — the agentic-loop brain (port 8082)"
  say "    • tts           — Kokoro neural text-to-speech (port 8880)"
  say "    • stt           — Whisper speech-to-text (port 8080)"
  say "    • searxng       — bundled meta-search for the browser tool"
  say ""
  say "  Ollama is on your host (not in Docker) and serves the LLM at :11434."
fi
echo

# Pick GPU overlay (same logic as build step)
case "$NODEAVA_PLATFORM" in
  linux|linux-wsl)
    if [[ -n "$NODEAVA_GPU" ]] && [[ "$NODEAVA_GPU" =~ NVIDIA ]]; then
      gpu_overlay="-f docker-compose.gpu-nvidia.yml"
    elif [[ -n "$NODEAVA_GPU" ]] && [[ "$NODEAVA_GPU" =~ (AMD|Radeon) ]]; then
      gpu_overlay="-f docker-compose.gpu-amd.yml"
    else
      gpu_overlay=""
    fi
    ;;
  mac) gpu_overlay="" ;;
  *) gpu_overlay="" ;;
esac

# Mac overlay: routes nginx STT/TTS to host.docker.internal (native services)
# + clears frontend.depends_on so it doesn't block waiting for Docker stt/tts
# (which don't run on Mac).
mac_overlay=""
[[ "$NODEAVA_PLATFORM" = "mac" ]] && mac_overlay="-f docker-compose.mac.yml"

cd "$NODEAVA_REPO_ROOT"

# Auto-write Blackwell-compatible TTS overlay (only when 02-preflight.sh
# detected sm_120). We use a DEDICATED filename rather than the generic
# docker-compose.override.yml — the override.yml filename is Docker
# Compose's standard local-dev convention (e.g., bind mounts, debug
# tooling) and squatting on it would silently clobber a user's customizations.
#
# Image-selection logic (best image first):
#   1. kokoro-fastapi-blackwell:nightly (local, PyTorch nightly w/ sm_120) — real GPU
#   2. ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4 (universal fallback, ~2-5s/sentence)
blackwell_overlay_file="$NODEAVA_REPO_ROOT/docker-compose.blackwell-tts.yml"
if [[ "${NODEAVA_GPU_BLACKWELL:-0}" == "1" ]]; then
  if docker image inspect kokoro-fastapi-blackwell:nightly >/dev/null 2>&1; then
    blackwell_image="kokoro-fastapi-blackwell:nightly"
    blackwell_mode="GPU (sm_120 image found locally)"
  else
    blackwell_image="ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4"
    blackwell_mode="CPU fallback (no local sm_120 image)"
  fi

  # Only rewrite if the target image differs from what's already pinned —
  # avoids touching the file on every wizard run.
  if [[ ! -f "$blackwell_overlay_file" ]] || ! grep -qF "image: $blackwell_image" "$blackwell_overlay_file"; then
    info "Writing Blackwell TTS overlay — $blackwell_mode..."
    if [[ "$blackwell_image" = "kokoro-fastapi-blackwell:nightly" ]]; then
      cat > "$blackwell_overlay_file" <<'EOF'
# Auto-generated by install.sh (08-up-stack) — DO NOT EDIT, will be rewritten.
# Blackwell GPU detected + local kokoro-fastapi-blackwell:nightly image found.
# Uses PyTorch nightly with sm_120 kernels for real GPU acceleration.
# To rebuild the image:
#   docker build -t kokoro-fastapi-blackwell:nightly docker/kokoro-blackwell/
# To remove this overlay (e.g., upstream Kokoro ships sm_120 support):
#   rm docker-compose.blackwell-tts.yml && ./install.sh
services:
  tts:
    image: kokoro-fastapi-blackwell:nightly
  # STT still needs CPU on Blackwell — whisper.cpp's Vulkan shaders crash
  # on sm_120 (exit 132). USE_GPU=0 makes the entrypoint pass --no-gpu.
  stt:
    environment:
      - USE_GPU=0
    deploy:
      resources:
        reservations:
          devices: []
EOF
    else
      cat > "$blackwell_overlay_file" <<'EOF'
# Auto-generated by install.sh (08-up-stack) — DO NOT EDIT, will be rewritten.
# Blackwell GPU detected; no local sm_120 image, so pin CPU variants.
# To switch TTS to GPU later, build the sm_120 image:
#   docker build -t kokoro-fastapi-blackwell:nightly docker/kokoro-blackwell/
# then re-run ./install.sh (this file will auto-rewrite to the GPU image).
services:
  tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4
    environment:
      - DEVICE_TYPE=cpu
    deploy:
      resources:
        reservations:
          devices: []
  # STT: whisper.cpp Vulkan shaders crash on Blackwell (sm_120), exit 132.
  # USE_GPU=0 makes the entrypoint pass --no-gpu to whisper-server.
  # Whisper base.en on CPU is ~1-3s per turn — slower than Vulkan but fine.
  stt:
    environment:
      - USE_GPU=0
    deploy:
      resources:
        reservations:
          devices: []
EOF
    fi
    ok "wrote $blackwell_overlay_file"
  fi
fi

# Stack overlays from broadest to narrowest, with the user's dev-time
# docker-compose.override.yml LAST so attendee customizations always win.
blackwell_overlay=""
[[ -f "$blackwell_overlay_file" ]] && blackwell_overlay="-f docker-compose.blackwell-tts.yml"

user_override_overlay=""
if [[ -f "$NODEAVA_REPO_ROOT/docker-compose.override.yml" ]]; then
  user_override_overlay="-f docker-compose.override.yml"
fi

# Service list — Mac runs stt/tts natively, so don't try to start them in
# Docker. start-mac.sh launches them as host processes.
if [[ "$NODEAVA_PLATFORM" = "mac" ]]; then
  services_to_start=(orchestrator searxng frontend)
else
  services_to_start=(orchestrator tts stt searxng frontend)
fi

info "Starting services ..."
# `|| true`: compose's depends_on can declare a dependency 'failed' if a slow-
# starting container hasn't passed its healthcheck before depends_on timing
# out (CPU TTS first-boot downloads ~330MB model weights, ~20-60s on a fast
# laptop). The dependent container then isn't created and `up -d` exits non-
# zero. Our own wait loop below handles the slow case correctly, so don't let
# compose's verdict abort the wizard.
# shellcheck disable=SC2086
docker compose -f docker-compose.yml $mac_overlay $gpu_overlay $blackwell_overlay $user_override_overlay up -d "${services_to_start[@]}" || true

# Wait for healthy. 240s ceiling accommodates CPU TTS first-boot (model
# download + warmup); GPU TTS is normally <30s.
# A line is OK if Health is "healthy" OR empty (service has no healthcheck —
# e.g. searxng before it implements one, or the frontend nginx container).
# A line is BLOCKING if Health is "starting" or "unhealthy".
deadline=$(( $(date +%s) + 240 ))
while true; do
  # shellcheck disable=SC2086
  blocking="$(docker compose -f docker-compose.yml $mac_overlay $gpu_overlay $blackwell_overlay $user_override_overlay ps --format '{{.Name}} {{.Health}}' 2>/dev/null | grep -E ' (starting|unhealthy)$' || true)"
  [[ -z "$blocking" ]] && break
  if [[ "$(date +%s)" -gt "$deadline" ]]; then
    warn "Some services did not become healthy within 240s:"
    echo "$blocking" | sed 's/^/  /'
    break
  fi
  sleep 3
done

# Re-up — some containers may have been skipped earlier when their depends_on
# was deemed failed. Now that deps are healthy this becomes a no-op for
# already-running containers and creates anything missing.
# shellcheck disable=SC2086
docker compose -f docker-compose.yml $mac_overlay $gpu_overlay $blackwell_overlay $user_override_overlay up -d "${services_to_start[@]}" >/dev/null 2>&1 || true

# Final state report
# shellcheck disable=SC2086
final_unhealthy="$(docker compose -f docker-compose.yml $mac_overlay $gpu_overlay $blackwell_overlay $user_override_overlay ps --format '{{.Name}} {{.Health}}' 2>/dev/null | grep -E ' (starting|unhealthy)$' || true)"
if [[ -z "$final_unhealthy" ]]; then
  ok "Stack is up."
  if [[ "$NODEAVA_PLATFORM" = "mac" ]]; then
    echo
    info "Next: launch native STT + TTS:"
    say  "  bash scripts/start-mac.sh"
  fi
else
  warn "Stack is up, but these services are not yet healthy:"
  echo "$final_unhealthy" | sed 's/^/  /'
  warn "Step 9 smoke checks may report failures; re-run install.sh in a minute."
fi
pause
